png-flags for sunos
git-svn-id: file:///source/coreland/sysdeps/trunk@235 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/png-flags/png-flags b/SYSDEPS/png-flags/png-flags
--- a/SYSDEPS/png-flags/png-flags
+++ b/SYSDEPS/png-flags/png-flags
@@ -8,16 +8,51 @@ fatal()
   exit 111
 }
 
+search_headers()
+{
+  header="$1"
+  path="$2"
+
+  for d in ${path}
+  do
+    if [ -f "${d}/${header}" ]
+    then
+      ${echo} " -I${d} "
+      return 0
+    fi
+  done
+
+  # could not locate header
+  return 1
+}
+
+search="NO"
+header="png.h"
+
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
+  sunos)
+    path="/usr/local/include /usr/sfw/include "
+    search="YES"
+     ;;
   *) ;;
   esac
 fi
 
-# default libpng-config system
+# for systems that don't have libpng-config
+if [ "${search}" = "YES" ]
+then
+  search_headers "${header}" "${path}"
+  if [ $? -ne 0 ]
+  then
+    fatal "could not locate ${header}"
+  fi
+  exit 0
+fi
 
+# default libpng-config system
 flist=`libpng-config --I_opts --cppflags`
 err=$?
 flags=""
