PNG updates, now use libpng-config
git-svn-id: file:///source/coreland/sysdeps/trunk@233 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/png-flags/png-flags b/SYSDEPS/png-flags/png-flags
--- a/SYSDEPS/png-flags/png-flags
+++ b/SYSDEPS/png-flags/png-flags
@@ -8,60 +8,28 @@ fatal()
   exit 111
 }
 
-darwin_flags()
-{
-  if [ -f "/sw/include/png.h" ]
-  then
-    ${echo} " -I/sw/include "
-    return 0
-  fi
-
-  if [ -f "/sw/include/libpng12/png.h" ]
-  then
-    ${echo} " -I/sw/include/libpng12 "
-    return 0
-  fi
-
-  if [ -f "/usr/local/include/png.h" ]
-  then
-    ${echo} " -I/usr/local/include "
-    return 0
-  fi
-}
-
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
-  darwin)
-    # XXX: darwin doesn't necessarily mean OS X, but there doesn't
-    #      seem to be a reliable way to test for OS X specifically
-    darwin_flags
-    if [ $? -ne 0 ]
-    then
-      fatal "could not locate SDL includes"
-    fi
-
-    exit 0
-  ;;
   *) ;;
   esac
 fi
 
-# fall-through system
+# default libpng-config system
 
-if [ -f "/usr/local/include/png.h" ]
+flist=`libpng-config --I_opts --cppflags`
+err=$?
+flags=""
+
+if [ ${err} -ne 0 ]
 then
-  png="-I/usr/local/include"
-  ${echo} " ${cf} ${png} "
-  exit 0
+  fatal "could not locate libPNG includes"
 fi
 
-if [ -f "/usr/local/include/libpng/png.h" ]
-then
-  gl="-I/usr/local/include"
-  ${echo} " ${cf} ${png} "
-  exit 0
-fi
+for f in ${flist}
+do
+  flags="${flags} $f"
+done
 
-fatal "could not locate libPNG includes"
+echo ${flags}
diff --git a/SYSDEPS/png-libs/png-libs b/SYSDEPS/png-libs/png-libs
--- a/SYSDEPS/png-libs/png-libs
+++ b/SYSDEPS/png-libs/png-libs
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+#!/bin/sh
+
 echo="/bin/echo -n"
 
 fatal()
@@ -8,47 +10,28 @@ fatal()
   exit 111
 }
 
-search_libs()
-{
-  lib="$1"
-  path="$2"
-  args="$3"
-
-  for d in ${path}
-  do
-    if [ -f "${d}/${lib}" ]
-    then
-      ${echo} " -L${d} ${args}"
-      return 0
-    fi
-  done
-
-  # could not locate lib
-  return 1
-}
-
-lib="libpng.so"
-path="/usr/X11R6/lib /usr/X11R7/lib /usr/local/lib"
-args="-lpng"
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
-  darwin)
-    path="/usr/local/lib /sw/lib ${path}"
-    lib="libpng.dylib"
-  ;;
-  sunos)
-    path="/usr/local/lib /usr/sfw/lib ${path}"
-  ;;
-  *)
-  ;;
+  *) ;;
   esac
 fi
 
-search_libs "${lib}" "${path}" "${args}"
-if [ $? -ne 0 ]
+# default libpng-config system
+
+flist=`libpng-config --ldflags`
+err=$?
+flags=""
+
+if [ ${err} -ne 0 ]
 then
-  fatal "could not locate ${lib}"
+  fatal "could not locate PNG libs"
 fi
-exit 0
+
+for f in ${flist}
+do
+  flags="${flags} $f"
+done
+
+echo ${flags}
