updated project tools and regenerated makefiles.
git-svn-id: file:///source/coreland/sysdeps/trunk@2486 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/cc-compile b/cc-compile
--- a/cc-compile
+++ b/cc-compile
@@ -14,6 +14,20 @@ then
 fi
 CFLAGS="${CFLAGS} `head -n 1 conf-cflags 2>/dev/null`"
 
+SYSTYPE=`head -n 1 conf-systype`
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not read conf-systype" 1>&2
+  exit 1
+fi
+
+CCTYPE=`head -n 1 conf-cctype`
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not read conf-cctype" 1>&2
+  exit 1
+fi
+
 # read in optional flag file
 if [ -f "conf-ccfflist" ]
 then
@@ -38,5 +52,31 @@ then
     CFLAGS="${CFLAGS} ${FLAGS}"
   done
 fi
+
+case ${CCTYPE} in
+  GCC)
+    case ${SYSTYPE} in
+      DARWIN)
+        # On Darwin >= 8, produce fat binaries
+        release=`uname -r | awk -F. '{print $1}'`
+        if [ ${release} -gt 7 ]
+        then
+          if [ -d /Developer/SDKs/MacOSX10.4u.sdk ]
+          then
+            exec ${CC} \
+              -arch ppc \
+              -arch i386 \
+              -isysroot /Developer/SDKs/MacOSX10.4u.sdk \
+              -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
+          fi
+        fi
+        ;;
+      *)
+        ;;
+    esac
+    ;;
+  *)
+    ;;
+esac
 
 exec ${CC} -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
diff --git a/cc-link b/cc-link
--- a/cc-link
+++ b/cc-link
@@ -14,6 +14,20 @@ then
 fi
 LDFLAGS="${LDFLAGS} `head -n 1 conf-ldflags 2>/dev/null`"
 
+SYSTYPE=`head -n 1 conf-systype`
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not read conf-systype" 1>&2
+  exit 1
+fi  
+  
+LDTYPE=`head -n 1 conf-ldtype`
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not read conf-ldtype" 1>&2
+  exit 1
+fi
+
 if [ -f "conf-ldfflist" ]
 then
   for f in `cat "conf-ldfflist"`
@@ -36,5 +50,31 @@ then
     LDFLAGS="${LDFLAGS} ${FLAGS}"
   done
 fi
+
+case ${LDTYPE} in
+  GCC)
+    case ${SYSTYPE} in
+      DARWIN)
+        # On Darwin >= 8, produce fat binaries
+        release=`uname -r | awk -F. '{print $1}'`
+        if [ ${release} -gt 7 ]
+        then
+          if [ -d /Developer/SDKs/MacOSX10.4u.sdk ]
+          then
+            exec ${LD} \
+              -arch ppc \
+              -arch i386 \
+              -isysroot /Developer/SDKs/MacOSX10.4u.sdk \
+              -o ${out} ${1+"$@"} ${LDFLAGS}
+          fi
+        fi
+        ;;
+      *)
+        ;;
+    esac
+    ;;
+  *)
+    ;;
+esac
 
 exec ${LD} -o ${out} ${1+"$@"} ${LDFLAGS}
