vms fixes
git-svn-id: file:///source/coreland/sysdeps/trunk@2196 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/mk-cctype b/mk-cctype
--- a/mk-cctype
+++ b/mk-cctype
@@ -180,7 +180,7 @@ fi
 ./_mk_cctype
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not create _mk_cctype" 1>&2
+  echo "fatal: could not execute _mk_cctype" 1>&2
   cleanup
   exit 1
 fi
diff --git a/mk-systype b/mk-systype
--- a/mk-systype
+++ b/mk-systype
@@ -119,7 +119,7 @@ int main()
 #if defined(sco) || defined(_UNIXWARE7)
   var = "UNIXWARE";
 #endif
-#if defined(____VMS_VER)
+#if defined(__VMS_VER) || defined(VMS) || defined(__VMS)
   var = "VMS";
 #endif
 #if defined(__MVS__) || defined(__HOS_MVS__) || defined(__TOS_MVS__)
@@ -147,7 +147,7 @@ fi
 ./_mk_systype
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not create _mk_systype" 1>&2
+  echo "fatal: could not execute _mk_systype" 1>&2
   cleanup
   exit 1
 fi
