Update sd-defines to handle new defines data format.

diff --git a/SYSDEPS/sd-defines b/SYSDEPS/sd-defines
--- a/SYSDEPS/sd-defines
+++ b/SYSDEPS/sd-defines
@@ -13,7 +13,7 @@ for module in ${MODULES}
 do
   if [ -f modules/${module}/defines ]
   then
-    defines=`cat modules/${module}/defines` ||
+    defines=`cat modules/${module}/defines | awk -F: '{print $1}'` ||
       fatal "could not read modules/${module}/defines"
 
     for define in ${defines}
@@ -23,7 +23,13 @@ do
 
     if [ -d modules/${module}/os_ext ]
     then
-      cat modules/${module}/os_ext/*/defines 2>/dev/null
+      for dir in `ls modules/${module}/os_ext/`
+      do
+        if [ -f ${dir}/defines ]
+        then
+          cat ${dir}/defines | awk -F: '{print $1}' || fatal "could not read ${dir}/defines"
+        fi
+      done
     fi
   fi
 done
