Clean up sd-defines.

diff --git a/SYSDEPS/sd-defines b/SYSDEPS/sd-defines
--- a/SYSDEPS/sd-defines
+++ b/SYSDEPS/sd-defines
@@ -1,16 +1,29 @@
 #!/bin/sh
 
-for mod in `ls modules`
+fatal()
+{
+  echo "sd-defines: fatal: $1" 1>&2
+  exit 1
+}
+
+MODULES=`ls modules`             || fatal "could not list modules"
+MODULES=`echo ${MODULES} | sort` || fatal "could not sort modules"
+
+for module in ${MODULES}
 do
-  if [ -f modules/$mod/defines ]
+  if [ -f modules/${module}/defines ]
   then
-    for def in `cat modules/$mod/defines`
+    defines=`cat modules/${module}/defines` ||
+      fatal "could not read modules/${module}/defines"
+
+    for define in ${defines}
     do
-      echo $def
+      echo "${define}" || fatal "could not write define"
     done
-    if [ -d modules/$mod/os_ext ]
+
+    if [ -d modules/${module}/os_ext ]
     then
-      cat modules/$mod/os_ext/*/defines 2>/dev/null
+      cat modules/${module}/os_ext/*/defines 2>/dev/null
     fi
   fi
 done
