Clean up sd-genmk.

diff --git a/SYSDEPS/sd-genmk b/SYSDEPS/sd-genmk
--- a/SYSDEPS/sd-genmk
+++ b/SYSDEPS/sd-genmk
@@ -1,69 +1,143 @@
 #!/bin/sh
 
-echo '#----------------------------------------------------------------------'
-echo '# SYSDEPS start'
-echo
+fatal()
+{
+  echo "sd-genmk: fatal: $1" 1>&2
+  exit 1
+}
 
-for module in `ls modules | sort`
+#
+# List and sort modules.
+#
+
+MODULES=`ls modules`             || fatal "could not list modules"
+MODULES=`echo ${MODULES} | sort` || fatal "could not sort modules"
+
+#
+# Write Makefile "header".
+#
+
+(
+cat <<EOF
+#----------------------------------------------------------------------
+# SYSDEPS start
+
+EOF
+) || fatal "could not write header"
+
+#
+# Write targets for executing modules.
+#
+
+for module in ${MODULES}
 do
   if [ -f modules/$module/creates ]
   then
-    files=`cat modules/$module/creates`
+    files=`cat modules/$module/creates` ||
+      fatal "could not read modules/$module/creates"
+
     first_done=0
-    # flatten files to a string
+    # Flatten files to a string.
     flat_files=""
+
     for file in $files; do flat_files="$file ${flat_files}"; done
-    for file in `cat modules/$module/creates`
+    for file in ${files}
     do
       if [ $first_done -eq 0 ]
       then
         first=$file
         first_done=1
-        # note that hard tab characters are embedded here
+        # Note that hard tab characters are embedded here
+        (
         cat <<EOF
 $file:
 	@echo SYSDEPS $module run create $flat_files
 	@(cd SYSDEPS && ./sd-run modules/$module)
 EOF
+) || fatal "could not write makefile target"
       else
+(
 cat <<EOF
 $file: $first
 EOF
+) || fatal "could not write makefile target"
       fi
     done
   fi
 done
-echo
-echo
 
-for module in `ls modules | sort`
+# This whitespace is significant - it terminates the list of
+# dependencies for the above target.
+
+(
+cat <<EOF
+
+
+EOF
+) || fatal "could not write whitespace"
+
+#
+# Write targets for cleaning modules.
+#
+
+for module in ${MODULES}
 do
   if [ -f modules/$module/creates ]
   then
-    files=`cat modules/$module/creates`
-    # flatten files to a string
+    files=`cat modules/$module/creates` ||
+      fatal "could not read modules/$module/creates"
+
+    # Flatten files to a string.
     flat_files=""
     for file in $files; do flat_files="$file ${flat_files}"; done
-    # note that hard tab characters are embedded here
+
+    # Note that hard tab characters are embedded here.
+    (
     cat <<EOF
 ${module}_clean:
 	@echo SYSDEPS $module clean $flat_files
 	@(cd SYSDEPS && ./sd-clean modules/$module)
 EOF
+    ) || fatal "could not write makefile target"
   fi
 done
-echo
-echo
 
-echo "sysdeps_clean:\\"
-for module in `ls modules | sort`
+# This whitespace is significant - it terminates the list of
+# dependencies for the above target.
+
+(
+cat <<EOF
+
+
+EOF
+) || fatal "could not write whitespace"
+
+#
+# Main 'clean' target.
+#
+
+echo "sysdeps_clean:\\" ||
+  fatal "could not write main clean target"
+
+for module in ${MODULES}
 do
   if [ -f modules/$module/creates ]
   then
-    echo "${module}_clean \\"
+    echo "${module}_clean \\" ||
+      fatal "could not write ${module}_clean target"
   fi
 done
-echo
-echo
-echo '# SYSDEPS end'
-echo '#----------------------------------------------------------------------'
+
+#
+# Makefile 'footer'.
+#
+
+(
+cat <<EOF
+
+
+
+# SYSDEPS end
+#----------------------------------------------------------------------
+EOF
+) || fatal "could not write Makefile footer"
