fail on compiler missing
git-svn-id: file:///source/coreland/sysdeps/trunk@1543 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/sysdep-subs b/SYSDEPS/sysdep-subs
--- a/SYSDEPS/sysdep-subs
+++ b/SYSDEPS/sysdep-subs
@@ -15,6 +15,12 @@ then
   tmp=`head -n 1 "../conf-cc"`
   if [ ! -z "${tmp}" ]; then SYSDEP_CC="${tmp}"; fi
 fi
+which ${SYSDEP_CC}
+if [ $? -ne 0 ]
+then
+  ${SYSDEP_DIR_RELATIVE}/sd-error "could not locate usable compiler"
+  exit 112
+fi
 export SYSDEP_CC
 
 #
