moving to new design
SYSD_HAVE_*



git-svn-id: file:///source/coreland/sysdeps/trunk@391 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/sysdep-subs b/SYSDEPS/sysdep-subs
--- a/SYSDEPS/sysdep-subs
+++ b/SYSDEPS/sysdep-subs
@@ -1,9 +1,8 @@
 #!/bin/sh
 
-fatal()
+error()
 {
-  echo "fatal: $1" 1>&2
-  exit 111
+  echo "error: $1" 1>&2
 }
 
 search_header()
