updates sysdep-subs
git-svn-id: file:///source/coreland/sysdeps/trunk@241 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/sdl-flags/sdl-flags b/SYSDEPS/sdl-flags/sdl-flags
--- a/SYSDEPS/sdl-flags/sdl-flags
+++ b/SYSDEPS/sdl-flags/sdl-flags
@@ -1,58 +1,41 @@
 #!/bin/sh
 
-fatal()
-{
-  echo "fatal: $1" 1>&2
+. ../sysdep-subs
+if [ $? -ne 0 ]
+then
   exit 111
-}
+fi
 
-darwin_flags()
-{
-  flg="-D_THREAD_SAFE"
-
-  # sdl-config gives wrong answers, like /sw/include/SDL instead of the
-  # correct /sw/include.
-
-  if [ -f "/Library/Frameworks/SDL.framework/Headers/SDL.h" ]
-  then
-    echo " -I/Library/Frameworks/SDL.framework/Headers "
-    return 0
-  fi
-
-  if [ -f "/usr/local/include/SDL/SDL.h" ]
-  then
-    echo " -I/usr/local/include ${flg} "
-    return 0
-  fi
-
-  if [ -f "/sw/include/SDL/SDL.h" ]
-  then
-    echo " -I/sw/include ${flg} "
-    return 0
-  fi
-}
+search="NO"
+header="SDL.h"
+path="/usr/local/include/SDL"
 
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
   darwin)
-    # XXX: darwin doesn't necessarily mean OS X, but there doesn't
-    #      seem to be a reliable way to test for OS X specifically
-    darwin_flags
-    if [ $? -ne 0 ]
-    then
-      fatal "could not locate SDL includes"
-    fi
-
-    exit 0
-  ;;
-  *) ;;
+    path="/Library/Frameworks/SDL.framework/Headers \
+          /sw/include/SDL ${path}"
+    args="-D_THREAD_SAFE"
+    search="YES"
+    ;;
+  *)
+    ;;
   esac
 fi
 
-# fall-through system
+if [ "${search}" = "YES" ]
+then
+  search_for "${header}" "${path}" "${args}"
+  if [ $? -ne 0 ]
+  then
+    fatal "could not locate ${header}"
+  fi
+  exit 0
+fi
 
+# default sdl-config system
 cf="`sdl-config --cflags`"
 if [ $? -ne 0 ]
 then
diff --git a/SYSDEPS/sdl-image-flags/sdl-image-flags b/SYSDEPS/sdl-image-flags/sdl-image-flags
--- a/SYSDEPS/sdl-image-flags/sdl-image-flags
+++ b/SYSDEPS/sdl-image-flags/sdl-image-flags
@@ -1,51 +1,42 @@
 #!/bin/sh
 
-fatal()
-{
-  echo "fatal: $1" 1>&2
+. ../sysdep-subs
+if [ $? -ne 0 ]
+then
   exit 111
-}
+fi
 
-darwin_flags()
-{
-  if [ -d "/Library/Frameworks/SDL_image.framework/Headers" ]
-  then
-    echo " -I/Library/Frameworks/SDL_image.framework/Headers "
-    return 0
-  fi
-
-  if [ -f "/usr/local/include/SDL/SDL_image.h" ]
-  then
-    echo " -I/usr/local/include/SDL "
-    return 0
-  fi
-
-  if [ -f "/sw/include/SDL/SDL_image.h" ]
-  then
-    echo " -I/sw/include/SDL "
-    return 0
-  fi
-}
+search="NO"
+header="SDL_image.h"
+path="/usr/local/include/SDL"
 
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
   darwin)
-    # XXX: darwin doesn't necessarily mean OS X, but there doesn't
-    #      seem to be a reliable way to test for OS X specifically
-    darwin_flags
-    if [ $? -ne 0 ]
-    then
-      fatal "could not locate SDL includes"
-    fi
-
-    exit 0
-  ;;
-  *) ;;
+    path="/Library/Frameworks/SDL_image.framework/Headers \
+          /sw/include/SDL ${path}"
+    search="YES"
+    ;;
+  sunos)
+    path="/opt/csw/include/SDL ${path}"
+    search="YES"
+    ;;
+  *)
+    search="YES"
+    ;;
   esac
 fi
 
-# fall-through system
+if [ "${search}" = "YES" ]
+then
+  search_for "${header}" "${path}" "${args}"
+  if [ $? -ne 0 ]
+  then
+    fatal "could not locate ${header}"
+  fi
+  exit 0
+fi
 
-echo "-I/usr/local/include/SDL " 
+# can't get here
diff --git a/SYSDEPS/sdl-libs/sdl-libs b/SYSDEPS/sdl-libs/sdl-libs
--- a/SYSDEPS/sdl-libs/sdl-libs
+++ b/SYSDEPS/sdl-libs/sdl-libs
@@ -1,56 +1,41 @@
 #!/bin/sh
 
-fatal()
-{
-  echo "fatal: $1" 1>&2
+. ../sysdep-subs
+if [ $? -ne 0 ]
+then
   exit 111
-}
+fi
 
-darwin_libs()
-{
-  lib="libSDLmain.a"
-  str="-framework SDL -framework Cocoa -framework OpenGL" # XXX: OpenGL?
-
-  if [ -f "/usr/local/lib/${lib}" ]
-  then
-    alib="/usr/local/lib/${lib}"
-    echo " ${alib} ${str} "
-    return 0
-  fi
-
-  if [ -f "/sw/lib/${lib}" ]
-  then
-    alib="/sw/lib/${lib}"
-    echo " ${alib} ${str} "
-    return 0
-  fi
-  
-  # could not locate libSDLmain.a
-  return 1
-}
+search="NO"
+path="/usr/local/lib"
+lib="libSDLmain.a"
 
 sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
 if [ x"$sys" != x ]
 then
   case "$sys" in
   darwin)
-    # XXX: darwin doesn't necessarily mean OS X, but there doesn't
-    #      seem to be a reliable way to test for OS X specifically
-    darwin_libs
-    if [ $? -ne 0 ]
-    then
-      fatal "could not locate libSDLmain.a"
-    fi
-
+    path="/sw/lib ${path}"
+    args="-framework SDL -framework Cocoa -framework OpenGL"
+    search="YES"
     exit 0
-  ;;
-  *) ;;
+    ;;
+  *)
+    ;;
   esac
 fi
 
-# fall-through generic platform
-# works on FreeBSD 6 at least
+if [ "${search}" = "YES" ]
+then
+  search_for "${lib}" "${path}" "${args}"
+  if [ $? -ne 0 ]
+  then
+    fatal "could not locate ${lib}"
+  fi
+  exit 0
+fi
 
+# fall-through generic platform
 str="`sdl-config --libs`"
 if [ $? -ne 0 ]
 then
