All modules rewritten to use new format.

diff --git a/SYSDEPS/modules/sd-math/custom b/SYSDEPS/modules/sd-math/custom
--- a/SYSDEPS/modules/sd-math/custom
+++ b/SYSDEPS/modules/sd-math/custom
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. "${SYSDEP_SUBS_FILE}" || exit 1
+
 libs_out="$1"
 flag_out="$2"
 head_out="$3"
@@ -11,7 +13,13 @@ M_HAVE=0
 
 cleanup()
 {
-  rm -f trymath1 trymath1.o
+  ${SYSDEP_UTIL_RM} -f trymath1 trymath1.o
+}
+
+fatal()
+{
+  cleanup
+  SYSDEP_FATAL "$1"
 }
 
 try_math()
@@ -23,10 +31,10 @@ try_math()
 
   if [ $? -eq 0 ]
   then
-    echo "${M_FLAGS}" >> "${flag_out}"
-    echo "${M_LIBS}" >> "${libs_out}"
-    echo "math-flags: ${M_FLAGS}" >> "${sysd_out}"
-    echo "math-libs: ${M_LIBS}" >> "${sysd_out}"
+    ${SYSDEP_UTIL_ECHO} "${M_FLAGS}" >> "${flag_out}"
+    ${SYSDEP_UTIL_ECHO} "${M_LIBS}" >> "${libs_out}"
+    ${SYSDEP_UTIL_ECHO} "sd-math-flags: ${M_FLAGS}" >> "${sysd_out}"
+    ${SYSDEP_UTIL_ECHO} "sd-math-libs: ${M_LIBS}" >> "${sysd_out}"
     M_HAVE=1
     cleanup
     return 0
@@ -37,37 +45,54 @@ try_math()
 
 try_math_funcs()
 {
-  echo "#ifndef _SD_MATH_H" >> "${head_out}"
-  echo "#define _SD_MATH_H" >> "${head_out}"
-  echo >> "${head_out}"
+  ${SYSDEP_UTIL_CAT} >> "${head_out}" << EOF
+#ifndef _SD_MATH_H
+#define _SD_MATH_H
 
-  if [ ! -d tmp ]; then mkdir tmp; fi
+EOF
 
-  for fn in `ls math_funcs`
+  if [ ! -d tmp ]
+  then
+    ${SYSDEP_UTIL_MKDIR} tmp || fatal "could not create tmp"
+  fi
+
+  FUNC_PATHS=`${SYSDEP_UTIL_ECHO} math_funcs/*` ||
+    fatal "could not list math functions"
+
+  for math_func_path in ${FUNC_PATHS}
   do
-    FUNC=`echo ${fn} | tr [a-z] [A-Z]`
+    math_func=`${SYSDEP_UTIL_BASENAME} ${math_func_path}` ||
+      fatal "could not retrieve name of function"
+    FUNC=`${SYSDEP_UTIL_ECHO} ${math_func} | ${SYSDEP_UTIL_TR} [a-z] [A-Z]` ||
+      fatal "could not convert name to uppercase"
+
     ${SYSDEP_CC} ${SYSDEP_CFLAGS} ${M_FLAGS} \
-      -c -o tmp/${fn}.o math_funcs/${fn}/${fn}.c 1>/dev/null 2>&1
+      -c -o tmp/${math_func}.o math_funcs/${math_func}/${math_func}.c 1>/dev/null 2>&1
     ${SYSDEP_LD} \
-      -o tmp/${fn} tmp/${fn}.o ${SYSDEP_LDFLAGS} ${M_LIBS} 1>/dev/null 2>&1
+      -o tmp/${math_func} tmp/${math_func}.o ${SYSDEP_LDFLAGS} ${M_LIBS} 1>/dev/null 2>&1
 
     if [ $? -eq 0 ]
     then
-      echo "#define HAVE_MATH_${FUNC}" >> "${head_out}"
-      funcs="${fn} ${funcs}"
+      ${SYSDEP_UTIL_ECHO} "#define SD_HAVE_MATH_${FUNC} 1" >> "${head_out}"
+      funcs="${math_func} ${funcs}"
     fi
-    rm -f tmp/${fn} tmp/${fn}.o
+
+    ${SYSDEP_UTIL_RM} -f tmp/${math_func} tmp/${math_func}.o ||
+      fatal "could not remove temporary files"
   done
 
-  echo >> "${head_out}"
-  echo "#endif" >> "${head_out}"
-  echo "math-funcs: ${funcs}" >> "${sysd_out}"
+  ${SYSDEP_UTIL_CAT} >> "${head_out}" << EOF
+
+#endif
+EOF
+
+  ${SYSDEP_UTIL_ECHO} "sd-math-funcs: ${funcs}" >> "${sysd_out}"
   cleanup
-  exit 0
+  ${SYSDEP_UTIL_EXIT} 0
 }
 
 #
-# try combinations of flags and libs to get math libs
+# Try combinations of flags and libs to get math libs
 # order is, unfortunately, significant.
 #
 
@@ -82,7 +107,7 @@ try_math
 if [ $? -eq 0 ]; then try_math_funcs; fi
 
 #
-# fallback
+# Fallback.
 #
 
 try_math_funcs
diff --git a/SYSDEPS/modules/sd-posix_rt/custom b/SYSDEPS/modules/sd-posix_rt/custom
--- a/SYSDEPS/modules/sd-posix_rt/custom
+++ b/SYSDEPS/modules/sd-posix_rt/custom
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. "${SYSDEP_SUBS_FILE}" || exit 1
+
 libs_out="$1"
 flag_out="$2"
 head_out="$3"
@@ -11,7 +13,7 @@ PRT_HAVE=0
 
 cleanup()
 {
-  rm -f trylink trylink.o
+  ${SYSDEP_UTIL_RM} -f trylink trylink.o
 }
 
 try_posix_rt()
@@ -23,10 +25,10 @@ try_posix_rt()
  
   if [ $? -eq 0 ]
   then
-    echo "${PRT_FLAGS}" >> "${flag_out}"
-    echo "${PRT_LIBS}" >> "${libs_out}"
-    echo "posix_rt-flags: ${PRT_FLAGS}" >> "${sysd_out}"
-    echo "posix_rt-libs: ${PRT_LIBS}" >> "${sysd_out}"
+    ${SYSDEP_UTIL_ECHO} "${PRT_FLAGS}" >> "${flag_out}"
+    ${SYSDEP_UTIL_ECHO} "${PRT_LIBS}" >> "${libs_out}"
+    ${SYSDEP_UTIL_ECHO} "sd-posix_rt-flags: ${PRT_FLAGS}" >> "${sysd_out}"
+    ${SYSDEP_UTIL_ECHO} "sd-posix_rt-libs: ${PRT_LIBS}" >> "${sysd_out}"
     PRT_HAVE=1
     cleanup
     return 0
@@ -37,30 +39,47 @@ try_posix_rt()
 
 try_posix_rt_funcs()
 {
-  echo "#ifndef _SD_POSIX_RT_H" >> "${head_out}"
-  echo "#define _SD_POSIX_RT_H" >> "${head_out}"
-  echo >> "${head_out}"
+  ${SYSDEP_UTIL_CAT} >> "${head_out}" << EOF
+#ifndef _SD_POSIX_RT_H
+#define _SD_POSIX_RT_H
 
-  if [ ! -d tmp ]; then mkdir tmp; fi
+EOF
 
-  for fn in `ls functions`
+  if [ ! -d tmp ]
+  then
+    ${SYSDEP_UTIL_MKDIR} tmp || fatal "could not create tmp"
+  fi
+
+  RT_FUNCTIONS=`${SYSDEP_UTIL_ECHO} functions/*` ||
+    fatal "could not list rt functions"
+
+  for rt_func_path in ${RT_FUNCTIONS}
   do
-    FUNC=`echo ${fn} | tr [a-z] [A-Z]`
+    rt_func=`${SYSDEP_UTIL_BASENAME} ${rt_func_path}` || 
+      fatal "could not retrieve function name"
+
+    FUNC=`${SYSDEP_UTIL_ECHO} ${rt_func} | tr [a-z] [A-Z]`
+
     ${SYSDEP_CC} ${SYSDEP_CFLAGS} ${PRT_FLAGS} \
-      -c -o tmp/${fn}.o functions/${fn}/${fn}.c 1>/dev/null 2>&1
+      -c -o tmp/${rt_func}.o functions/${rt_func}/${rt_func}.c 1>/dev/null 2>&1
     ${SYSDEP_LD} \
-      -o tmp/${fn} tmp/${fn}.o ${SYSDEP_LDFLAGS} ${PRT_LIBS} 1>/dev/null 2>&1
+      -o tmp/${rt_func} tmp/${rt_func}.o ${SYSDEP_LDFLAGS} ${PRT_LIBS} 1>/dev/null 2>&1
+
     if [ $? -eq 0 ]
     then
-      echo "#define HAVE_${FUNC}" >> "${head_out}"
-      funcs="${fn} ${funcs}"
+      ${SYSDEP_UTIL_ECHO} "#define SD_HAVE_POSIX_RT_${FUNC} 1" >> "${head_out}"
+      funcs="${rt_func} ${funcs}"
     fi
-    rm -f tmp/${fn} tmp/${fn}.o
+    ${SYSDEP_UTIL_RM} -f tmp/${rt_func} tmp/${rt_func}.o ||
+      fatal "could not remove temporary files"
   done
 
-  echo >> "${head_out}"
-  echo "#endif" >> "${head_out}"
-  echo "posix_rt-funcs: ${funcs}" >> "${sysd_out}"
+  ${SYSDEP_UTIL_CAT} >> "${head_out}" <<EOF
+
+#endif
+EOF
+
+  ${SYSDEP_UTIL_ECHO} "sd-posix_rt-funcs: ${funcs}" >> "${sysd_out}"
   exit 0
 }
 
