updated integer modules to assist cross compilation
git-svn-id: file:///source/coreland/sysdeps/trunk@2532 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/modules/uint16/uint16 b/SYSDEPS/modules/uint16/uint16
--- a/SYSDEPS/modules/uint16/uint16
+++ b/SYSDEPS/modules/uint16/uint16
@@ -2,8 +2,9 @@
 
 cleanup()
 {
-  rm -f try_uint1 try_uint1.o try_uint1.1 try_uint1.2 \
-        try_uint2 try_uint2.o try_uint2.1 try_uint2.2
+  rm -f try_int1 try_int1.o \
+        try_int2 try_int2.o \
+        try_stdint try_stdint.o
 }
 
 fatal()
@@ -13,40 +14,57 @@ fatal()
   exit 1
 }
 
+have_it()
+{
+  type="$1"
+  extra="$2"
+
+  cat >> "${temp_f}" <<EOF
+#ifndef _UINT16_H
+#define _UINT16_H
+
+$extra
+typedef $type uint16;
+
+#endif
+EOF
+  echo "uint16: ${type}" >> "${temp_sys}"
+  cleanup
+  exit 0
+}
+
 temp_f="$1"
 temp_sys="$2"
-HAVE_SIZE=0
 
-${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_uint1.o try_uint1.c 1>/dev/null 2>&1
-${SYSDEP_LD} -o try_uint1 try_uint1.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
+${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_stdint.o try_stdint.c 1>/dev/null 2>&1
+${SYSDEP_LD} -o try_stdint try_stdint.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
 if [ $? -eq 0 ]
 then
-  ./try_uint1 1>> try_uint1.1 2>> try_uint1.2
+  have_it "uint16_t" "#include <stdint.h>"
+fi
+
+${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int1.o try_int1.c 1>/dev/null 2>&1
+${SYSDEP_LD} -o try_int1 try_int1.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
+if [ $? -eq 0 ]
+then
+  type=`./try_int1`
   if [ $? -eq 0 ]
   then
-    mv try_uint1.1 "${temp_f}"
-    mv try_uint1.2 "${temp_sys}"
-    HAVE_SIZE=1
+    have_it "${type}"
   else
-    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_uint2.o try_uint2.c 1>/dev/null 2>&1
-    ${SYSDEP_LD} -o try_uint2 try_uint2.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
+    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int2.o try_int2.c 1>/dev/null 2>&1
+    ${SYSDEP_LD} -o try_int2 try_int2.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
     if [ $? -eq 0 ]
     then
-      ./try_uint2 1>> try_uint2.1 2>> try_uint2.2
+      type=`./try_int2`
       if [ $? -eq 0 ]
       then
-        mv try_uint2.1 "${temp_f}"
-        mv try_uint2.2 "${temp_sys}"
-        HAVE_SIZE=1
+        have_it "${type}"
       fi
     fi
   fi
 fi
 
-if [ ${HAVE_SIZE} -eq 0 ]
-then
-  fatal "could not get unsigned 16 bit integer type"
-fi
-
+fatal "could not get unsigned 16 bit integer type"
 cleanup
 exit 0
