integer modules now fall back to config
float32 float64 updated for cross comp

byteorder now uses conf-byteorder


git-svn-id: file:///source/coreland/sysdeps/trunk@2534 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/SYSDEPS/modules/float64/float64 b/SYSDEPS/modules/float64/float64
--- a/SYSDEPS/modules/float64/float64
+++ b/SYSDEPS/modules/float64/float64
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-do_clean()
+cleanup()
 {
   rm -f float64_make float64_make.o
 }
@@ -8,18 +8,56 @@ do_clean()
 fatal()
 {
   echo "fatal: $1" 1>&2
-  do_clean
+  cleanup
   exit 1
+}
+
+have_it()
+{
+  type="$1"
+  cat >> ${temp64} << EOF
+#ifndef _FLOAT64_H
+#define _FLOAT64_H
+
+typedef %s float64;
+
+#endif
+EOF
+  cleanup
+  exit 0
 }
 
 temp64="$1"
 tempsys="$2"
 
-${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o float64_make.o float64_make.c
-${SYSDEP_LD} -o float64_make float64_make.o ${SYSDEP_LDFLAGS}
-if [ $? -ne 0 ]; then fatal "error compiling float64_make"; fi
-./float64_make 1>${temp64} 2>>${tempsys}
-if [ $? -ne 0 ]; then fatal "could not get 64-bit floats"; fi
+if [ ${SYSDEP_CROSS_COMPILE} -eq 0 ]
+then
+  ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o float64_make.o float64_make.c
+  ${SYSDEP_LD} -o float64_make float64_make.o ${SYSDEP_LDFLAGS}
+  if [ $? -ne 0 ]; then fatal "error compiling float64_make"; fi
+  type=`./float64_make`
+  if [ $? -eq 0 ];
+  then
+    have_it "${type}"
+  fi
+fi
 
-do_clean
+if [ -z "${type}" ]
+then
+  conf=`${SYSDEP_LINE} 1 < CONFIG`
+  type=`${SYSDEP_FILE} get "${conf}" ""`
+  if [ -z "${type}" ]
+  then
+    if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
+    then
+      fatal "cross compiling and unable to read ${conf}"
+    else
+      fatal "unable to find appropriate float64 type and unable to read ${conf}"
+    fi
+  else
+    have_it "${type}"
+  fi
+fi
+
+cleanup
 exit 0
